import React, { useState } from 'react';
import { InventoryItem, StoreBranch, PurchaseOrder } from '../types';
import { calculateDemandForecast, formatCurrency } from '../utils/inventoryUtils';
import { Sparkles, CloudRain, Sun, Flame, Users, TrendingUp, CheckCircle, ArrowRight, ShoppingCart } from 'lucide-react';

interface DemandForecastPanelProps {
  items: InventoryItem[];
  currentBranch: StoreBranch;
  currency: 'KRW' | 'VND' | 'USD';
  onGenerateBatchPO: (po: PurchaseOrder) => void;
}

export const DemandForecastPanel: React.FC<DemandForecastPanelProps> = ({
  items,
  currentBranch,
  currency,
  onGenerateBatchPO,
}) => {
  const [simulatedWeather, setSimulatedWeather] = useState(currentBranch.weatherCondition);
  const [simulatedTraffic, setSimulatedTraffic] = useState(currentBranch.footTrafficLevel);
  const [applyWeatherImpact, setApplyWeatherImpact] = useState(true);

  // Compute forecasts for all items
  const simulatedBranch: StoreBranch = {
    ...currentBranch,
    weatherCondition: simulatedWeather,
    footTrafficLevel: simulatedTraffic,
  };

  const forecastedItems = items.map((item) => {
    const forecast = calculateDemandForecast(item, simulatedBranch, applyWeatherImpact);
    return {
      item,
      ...forecast,
    };
  });

  const replenishmentNeeded = forecastedItems.filter((f) => f.recommendedOrder > 0);
  const totalRecommendedUnits = replenishmentNeeded.reduce((acc, curr) => acc + curr.recommendedOrder, 0);
  const totalOrderEstimatedCost = replenishmentNeeded.reduce((acc, curr) => acc + curr.recommendedOrder * curr.item.unitCost, 0);

  const handleCreateAutoPO = () => {
    if (replenishmentNeeded.length === 0) return;

    const newPO: PurchaseOrder = {
      id: `po-${Date.now()}`,
      orderNumber: `PO-GS-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${Math.floor(100 + Math.random() * 900)}`,
      createdAt: new Date().toISOString(),
      expectedDelivery: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
      supplier: 'GS Retail Central Logistics Center',
      items: replenishmentNeeded.map((r) => ({
        itemId: r.item.id,
        sku: r.item.sku,
        name: r.item.name,
        category: r.item.category,
        quantity: r.recommendedOrder,
        unitCost: r.item.unitCost,
        totalCost: r.recommendedOrder * r.item.unitCost,
      })),
      totalAmount: totalOrderEstimatedCost,
      status: 'Draft',
      notes: `Auto-generated by IntelliStock AI Forecast (${simulatedWeather}, ${simulatedTraffic})`,
    };

    onGenerateBatchPO(newPO);
  };

  return (
    <div className="space-y-6">
      {/* AI Engine Hero Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-[#004b87] to-[#0075c9] rounded-2xl p-5 sm:p-6 text-white shadow-md">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="bg-cyan-400/20 text-cyan-200 border border-cyan-400/30 text-xs font-bold px-2.5 py-0.5 rounded-full flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-cyan-300" /> IntelliStock Demand AI
              </span>
              <span className="text-xs text-slate-300">Model: GS-Retail Temporal Forecaster</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold tracking-tight">
              Predictive 7-Day Replenishment Simulator
            </h2>
            <p className="text-sm text-slate-200 mt-1 max-w-2xl">
              Factors in live micro-climate shifts, commuter traffic volume, and POS historical sales velocity to prevent stockouts and cut fresh food waste.
            </p>
          </div>

          {/* Quick Auto-PO Button */}
          <div className="bg-white/10 backdrop-blur-xs border border-white/20 rounded-xl p-4 flex flex-col sm:flex-row items-center gap-4">
            <div>
              <p className="text-xs text-cyan-200 font-semibold uppercase tracking-wider">
                Recommended Replenishment
              </p>
              <div className="text-xl font-bold text-white mt-0.5">
                {totalRecommendedUnits} units across {replenishmentNeeded.length} SKUs
              </div>
              <p className="text-xs text-slate-300 mt-0.5">
                Estimated Inbound: {formatCurrency(totalOrderEstimatedCost, currency)}
              </p>
            </div>
            <button
              id="generate-smart-po-btn"
              onClick={handleCreateAutoPO}
              disabled={replenishmentNeeded.length === 0}
              className="w-full sm:w-auto px-4 py-2.5 bg-cyan-400 hover:bg-cyan-300 text-slate-950 font-bold rounded-lg shadow-sm text-xs transition-colors flex items-center justify-center gap-2 whitespace-nowrap disabled:opacity-50"
            >
              <ShoppingCart className="w-4 h-4" />
              <span>Generate AI Purchase Order</span>
            </button>
          </div>
        </div>

        {/* Environmental Parameter Controls */}
        <div className="mt-6 pt-5 border-t border-white/15 grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          {/* Weather Simulation */}
          <div className="bg-white/10 rounded-lg p-2.5 border border-white/15">
            <span className="text-cyan-200 font-semibold block mb-1.5 flex items-center gap-1">
              <Sun className="w-3.5 h-3.5" /> Simulated Weather
            </span>
            <select
              id="weather-sim-select"
              value={simulatedWeather}
              onChange={(e) => setSimulatedWeather(e.target.value as any)}
              className="w-full bg-slate-800 text-white border border-slate-700 rounded px-2 py-1.5 font-medium focus:outline-hidden cursor-pointer"
            >
              <option value="Sunny & Hot (32°C)">Sunny & Hot (32°C) → Chilled / Ice Surge</option>
              <option value="Heavy Rain (21°C)">Heavy Rain (21°C) → Ramen / Hot Warmer Surge</option>
              <option value="Cool & Clear (18°C)">Cool & Clear (18°C) → Standard Baseline</option>
              <option value="Cold & Snowy (1°C)">Cold & Snowy (1°C) → Hot Drinks Surge</option>
            </select>
          </div>

          {/* Foot Traffic Simulation */}
          <div className="bg-white/10 rounded-lg p-2.5 border border-white/15">
            <span className="text-cyan-200 font-semibold block mb-1.5 flex items-center gap-1">
              <Users className="w-3.5 h-3.5" /> Commuter / Foot Traffic
            </span>
            <select
              id="traffic-sim-select"
              value={simulatedTraffic}
              onChange={(e) => setSimulatedTraffic(e.target.value as any)}
              className="w-full bg-slate-800 text-white border border-slate-700 rounded px-2 py-1.5 font-medium focus:outline-hidden cursor-pointer"
            >
              <option value="Peak Commuter Surge">Peak Commuter Surge (+25% Grab-and-Go)</option>
              <option value="Moderate Flow">Moderate Standard Flow</option>
              <option value="Night Owl Steady">Night Owl Late-Night Demand</option>
              <option value="Quiet">Quiet Off-Peak</option>
            </select>
          </div>

          {/* Environmental Factor Toggle */}
          <div className="bg-white/10 rounded-lg p-2.5 border border-white/15 flex flex-col justify-center">
            <span className="text-cyan-200 font-semibold block mb-1">Impact Engine</span>
            <label className="flex items-center gap-2 cursor-pointer mt-1">
              <input
                id="toggle-weather-impact"
                type="checkbox"
                checked={applyWeatherImpact}
                onChange={(e) => setApplyWeatherImpact(e.target.checked)}
                className="rounded border-slate-700 text-[#0075c9] focus:ring-0"
              />
              <span className="text-white text-xs">Apply micro-climate demand multipliers</span>
            </label>
          </div>
        </div>
      </div>

      {/* Forecast Item Cards / Grid */}
      <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-xs">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="font-bold text-slate-900 text-base">SKU-Level Demand Breakdown</h3>
            <p className="text-xs text-slate-500">
              Real-time recommendations based on target safety buffers and forecasted 7-day velocity.
            </p>
          </div>
          <span className="text-xs font-semibold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-md">
            Showing {forecastedItems.length} Products
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3.5">
          {forecastedItems.map(({ item, forecastUnitsNext7Days, recommendedOrder, confidenceScore, keyDrivers }) => {
            const isDeficit = recommendedOrder > 0;

            return (
              <div
                key={item.id}
                id={`forecast-card-${item.id}`}
                className={`border rounded-xl p-3.5 transition-all flex flex-col justify-between ${
                  isDeficit ? 'border-amber-200 bg-amber-50/20 shadow-xs' : 'border-slate-200 bg-white'
                }`}
              >
                <div>
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                        {item.category}
                      </span>
                      <h4 className="font-bold text-slate-900 text-sm">{item.name}</h4>
                    </div>
                    <span className="text-[11px] font-bold px-2 py-0.5 rounded-full bg-slate-100 text-slate-700 border border-slate-200">
                      {confidenceScore}% Conf.
                    </span>
                  </div>

                  {/* Stock vs Demand comparison */}
                  <div className="grid grid-cols-2 gap-2 mt-3 pt-3 border-t border-slate-100 text-xs">
                    <div className="bg-slate-50 p-2 rounded-lg border border-slate-100">
                      <span className="text-slate-500 text-[11px] block">Current On-Hand</span>
                      <strong className={`text-sm ${item.currentStock <= item.minThreshold ? 'text-rose-600' : 'text-slate-800'}`}>
                        {item.currentStock} units
                      </strong>
                    </div>
                    <div className="bg-cyan-50/60 p-2 rounded-lg border border-cyan-100">
                      <span className="text-cyan-800 text-[11px] block">7-Day Projected Demand</span>
                      <strong className="text-sm text-cyan-900">{forecastUnitsNext7Days} units</strong>
                    </div>
                  </div>

                  {/* Key Drivers */}
                  <div className="mt-2.5 space-y-1">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                      Forecast Influencers:
                    </span>
                    {keyDrivers.map((driver, idx) => (
                      <div
                        key={idx}
                        className="text-[11px] text-slate-600 flex items-center gap-1.5 bg-slate-50 px-2 py-1 rounded"
                      >
                        <TrendingUp className="w-3 h-3 text-[#0075c9] shrink-0" />
                        <span className="truncate">{driver}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Replenishment Action */}
                <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between">
                  <div>
                    <span className="text-[11px] text-slate-500 block">AI Recommended Order:</span>
                    <strong className={`text-sm ${recommendedOrder > 0 ? 'text-[#0075c9]' : 'text-slate-600'}`}>
                      {recommendedOrder > 0 ? `+${recommendedOrder} units` : 'Optimal (No Order)'}
                    </strong>
                  </div>

                  {recommendedOrder > 0 && (
                    <span className="text-[11px] font-semibold text-slate-600">
                      Cost: {formatCurrency(recommendedOrder * item.unitCost, currency)}
                    </span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
